In [1]:
from datascience import *

In [2]:
cones = Table.read_table('cones.csv')
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [3]:
cones.show(3)

In [4]:
cones.show?

Signature: cones.show(max_rows=0)
Docstring:
Display the table.

Args:
    ``max_rows``: Maximum number of rows to be output by the function

Returns:
    A subset of the Table with number of rows specified in ``max_rows``.
    First ``max_rows`` number of rows are displayed. If no value is passed
    for ``max_rows``, then the entire Table is returned.

Examples:

>>> t = Table().with_columns(
...    "column1", make_array("data1", "data2", "data3"),
...    "column2", make_array(86, 51, 32),
...    "column3", make_array("b", "c", "a"),
...    "column4", make_array(5, 3, 6)
... )


>>> t
column1 | column2 | column3 | column4
data1   | 86      | b       | 5
data2   | 51      | c       | 3
data3   | 32      | a       | 6

>>> t.show()
<IPython.core.display.HTML object>

>>> t.show(max_rows=2)
<IPython.core.display.HTML object>
File:      /lib/python3.13/site-packages/datascience/tables.py
Type:      method

In [5]:
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [6]:
cones.select('Flavor')

Flavor
strawberry
chocolate
chocolate
strawberry
chocolate
bubblegum

In [7]:
coens('Flavor','Price')

<class 'NameError'>: name 'coens' is not defined

In [8]:
cones('Flavor','Price')

<class 'TypeError'>: 'Table' object is not callable

In [9]:
cones.select('Flavor','Price')

Flavor     | Price
strawberry | 3.55
chocolate  | 4.75
chocolate  | 5.25
strawberry | 5.25
chocolate  | 5.25
bubblegum  | 4.75

In [10]:
cones.select('Color')

Color
pink
light brown
dark brown
pink
dark brown
pink

In [11]:
cones.drop('Color')

Flavor     | Price
strawberry | 3.55
chocolate  | 4.75
chocolate  | 5.25
strawberry | 5.25
chocolate  | 5.25
bubblegum  | 4.75

In [12]:
cones_no_color = cones.drop('Color')
cones_no_color

Flavor     | Price
strawberry | 3.55
chocolate  | 4.75
chocolate  | 5.25
strawberry | 5.25
chocolate  | 5.25
bubblegum  | 4.75

In [13]:
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [14]:
cones.where('Flavor','strawberry')

Flavor     | Color | Price
strawberry | pink  | 3.55
strawberry | pink  | 5.25

In [15]:
cones.sort('Price')

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
bubblegum  | pink        | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25

In [16]:
cones.sort('Price',descending=True)

Flavor     | Color       | Price
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
chocolate  | light brown | 4.75
bubblegum  | pink        | 4.75
strawberry | pink        | 3.55

In [17]:
# From https://github.com/erikgregorywebb/datasets/blob/master/nba-salaries.csv
nba = Table.read_table('nba_salaries.csv')
nba

rank | name             | position | team                   | salary   | season
1    | Shaquille O'Neal | C        | Los Angeles Lakers     | 17142000 | 2000
2    | Kevin Garnett    | PF       | Minnesota Timberwolves | 16806000 | 2000
3    | Alonzo Mourning  | C        | Miami Heat             | 15004000 | 2000
4    | Juwan Howard     | PF       | Washington Wizards     | 15000000 | 2000
5    | Scottie Pippen   | SF       | Portland Trail Blazers | 14795000 | 2000
6    | Karl Malone      | PF       | Utah Jazz              | 14000000 | 2000
7    | Larry Johnson    | F        | New York Knicks        | 11910000 | 2000
8    | Gary Payton      | PG       | Seattle SuperSonics    | 11020000 | 2000
9    | Rasheed Wallace  | PF       | Portland Trail Blazers | 10800000 | 2000
10   | Shawn Kemp       | C        | Cleveland Cavaliers    | 10780000 | 2000
... (9446 rows omitted)

In [18]:
nba.select('position','PG')

<class 'ValueError'>: The column "PG" is not in the table. The table contains these columns: rank, name, position, team, salary, season

In [23]:
point_guards_20 = nba.where('position','PG').where('season',2020)
point_guards_20

rank | name              | position | team                   | salary   | season
1    | Stephen Curry     | PG       | Golden State Warriors  | 40231758 | 2020
2    | Chris Paul        | PG       | Oklahoma City Thunder  | 38506482 | 2020
3    | Russell Westbrook | PG       | Houston Rockets        | 38506482 | 2020
4    | John Wall         | PG       | Washington Wizards     | 38199000 | 2020
8    | Kyle Lowry        | PG       | Toronto Raptors        | 34996296 | 2020
14   | Kemba Walker      | PG       | Boston Celtics         | 32742000 | 2020
16   | Mike Conley       | PG       | Utah Jazz              | 32511624 | 2020
17   | Kyrie Irving      | PG       | Brooklyn Nets          | 31742000 | 2020
21   | Damian Lillard    | PG       | Portland Trail Blazers | 29802321 | 2020
52   | Malcolm Brogdon   | PG       | Indiana Pacers         | 20000000 | 2020
... (72 rows omitted)

In [25]:
point_guards_20.sort('salary',descending=True)

rank | name              | position | team                   | salary   | season
1    | Stephen Curry     | PG       | Golden State Warriors  | 40231758 | 2020
2    | Chris Paul        | PG       | Oklahoma City Thunder  | 38506482 | 2020
3    | Russell Westbrook | PG       | Houston Rockets        | 38506482 | 2020
4    | John Wall         | PG       | Washington Wizards     | 38199000 | 2020
8    | Kyle Lowry        | PG       | Toronto Raptors        | 34996296 | 2020
14   | Kemba Walker      | PG       | Boston Celtics         | 32742000 | 2020
16   | Mike Conley       | PG       | Utah Jazz              | 32511624 | 2020
17   | Kyrie Irving      | PG       | Brooklyn Nets          | 31742000 | 2020
21   | Damian Lillard    | PG       | Portland Trail Blazers | 29802321 | 2020
52   | Malcolm Brogdon   | PG       | Indiana Pacers         | 20000000 | 2020
... (72 rows omitted)